### ISSUE TITLE
Recherche wie der Mobile Client umgesetzt wird

### ISSUE THREAD

**Issue by athaeck** [NickHaecker/Connecting-Minds-Mobile-Player#1]
Überlegen und Recherchieren wie der Client aufm Tablet oder ähnliches umgesetzt wird; 
Vue-Native: ist zwar Depricated aber vielleicht trotzdem möglich
Unity: ein zweites Unity Projekt der den Mobilen Client darstellt
Vue: Browser Anwendung, die Mobile First ist -> wird gehostet falls möglich über BW Cloud Server
Anderes

**Comment by SuzanJ** [comment]
Vue-Native: 
Vue-Native war eine Möglichkeit, Vue.js zur Entwicklung nativer mobiler Apps zu verwenden. Allerdings wurde Vue-Native offiziell als veraltet (deprecated) eingestuft, was bedeutet, dass es nicht mehr aktiv weiterentwickelt wird. Es kann daher riskant sein, dieses Framework für neue Projekte zu verwenden, da es wahrscheinlich nicht mit den neuesten Technologien und Plattformen kompatibel ist.

Unity: 
Unity ist eine leistungsstarke Spiele-Engine, die auch zur Entwicklung von nativen mobilen Apps verwendet werden kann. Wenn du Erfahrung mit Unity hast und das Projekt eine 3D- oder interaktive Komponente erfordert, könnte Unity eine gute Wahl sein. Unity unterstützt die Entwicklung für verschiedene Plattformen, einschließlich iOS und Android.

Vue (Browser-Anwendung): 
Wenn deine Anwendung "Mobile First" ist und hauptsächlich im Webbrowser auf mobilen Geräten genutzt wird, dann ist die Verwendung von Vue.js für die Entwicklung einer responsiven Webanwendung eine sinnvolle Option. Du kannst diese Anwendung dann hosten und über einen Cloud-Server bereitstellen, wie du es erwähnt hast. Dies ermöglicht eine breite Verfügbarkeit, da die Benutzer die Anwendung einfach über ihren Webbrowser aufrufen können.

Andere Optionen: 
Einige gängige Optionen sind Flutter (für plattformübergreifende Entwicklung), React Native (wenn du bereits React.js-Kenntnisse hast), Xamarin (für C#-Entwickler) und nativer iOS/Android-Entwicklung mit Swift oder Java/Kotlin.

**Comment by SuzanJ** [comment]
1. **React Native**: Dieses Framework ermöglicht die Entwicklung nativer mobiler Apps mit React, einer beliebten JavaScript-Bibliothek. Es erlaubt die plattformübergreifende Entwicklung für iOS und Android und bietet eine hohe Wiederverwendbarkeit von Code.

2. **Flutter**: Ein von Google entwickeltes UI-Toolkit, das die plattformübergreifende Entwicklung von nativen Apps ermöglicht. Flutter verwendet die Programmiersprache Dart und bietet eine schnelle Entwicklung und hohe Performance.

3. **Xamarin**: Eine plattformübergreifende Entwicklungsumgebung von Microsoft, die es ermöglicht, native Apps für iOS, Android und Windows mit der Programmiersprache C# zu erstellen.

4. **PhoneGap/Cordova**: Diese Frameworks ermöglichen die Entwicklung von mobilen Apps mit HTML, CSS und JavaScript. Der Code wird in einem Container verpackt und als native App ausgeführt. Sie bieten eine plattformübergreifende Entwicklungsmöglichkeit.

5. **Swift (iOS) / Kotlin (Android)**: Wenn du eine plattformspezifische Entwicklung bevorzugst, kannst du die offiziellen Sprachen für iOS (Swift) und Android (Kotlin) verwenden. Dies ermöglicht die volle Nutzung der Plattformfunktionen, erfordert jedoch separate Codebasen für jede Plattform.

6. **NativeScript**: Ein Open-Source-Framework, das es ermöglicht, plattformübergreifende mobile Anwendungen mit JavaScript, TypeScript oder Angular zu entwickeln und dabei native UI-Komponenten zu verwenden.

7. **Corona SDK**: Ein Framework für die Entwicklung von 2D-Spielen und Anwendungen mit Lua. Es ist besonders für Spieleentwickler geeignet.

8. **Appcelerator Titanium**: Ein Framework, das es ermöglicht, mobile Anwendungen mit JavaScript zu erstellen, wobei der Code in nativen Code übersetzt wird.

**Comment by athaeck** [comment]
Möglich wäre noch Vue mit Three.js wenn das möglich wäre, sollte aber eigentlich. Ich schau nachher nach nem Package.

**Comment by athaeck** [comment]
A frame

**Comment by xXM1M1stYLeXx** [comment]
Flutter, swift und Kotlin können ausgeschlossen werden.

**Comment by xXM1M1stYLeXx** [comment]
https://aframe.io/
